//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGMarketingDashboard.Resources.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As you use this dashboard please keep in mind a few things....
        /// </summary>
        public static string Alert_info {
            get {
                return ResourceManager.GetString("Alert_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bar chart uses a logarithmic scale on the Y axis in order show two sets of data that vary in amounts. Notice how conversions (relatively small numbers in green) are plotted on the chart at the bottom where the scale starts at 1 and increases to 100. The sessions (relatively large numbers in yellow) are plotted at the top of the chart where the scale goes quickly from 1,000 to 10,000. This approach allows two data sets of varying scale to exist in a stacked layout on the chart..
        /// </summary>
        public static string Alert_Paragraph_BarChart {
            get {
                return ResourceManager.GetString("Alert_Paragraph_BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to make this sample easy to download and install, all the data for this application is random for each date range. Therefore, as you navigate around the site you will encounter different values even as you select identical date ranges..
        /// </summary>
        public static string Alert_Paragraph_Data {
            get {
                return ResourceManager.GetString("Alert_Paragraph_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the Bar Chart.
        /// </summary>
        public static string Alert_Text_Title_BarChart {
            get {
                return ResourceManager.GetString("Alert_Text_Title_BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the Data.
        /// </summary>
        public static string Alert_Text_Title_Data {
            get {
                return ResourceManager.GetString("Alert_Text_Title_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        public static string Australia {
            get {
                return ResourceManager.GetString("Australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banners.
        /// </summary>
        public static string Banners {
            get {
                return ResourceManager.GetString("Banners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branded Searches.
        /// </summary>
        public static string Branded_Searches {
            get {
                return ResourceManager.GetString("Branded_Searches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brasil.
        /// </summary>
        public static string Brasil {
            get {
                return ResourceManager.GetString("Brasil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgaria.
        /// </summary>
        public static string Bulgaria {
            get {
                return ResourceManager.GetString("Bulgaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Medium.
        /// </summary>
        public static string By_Medium {
            get {
                return ResourceManager.GetString("By_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Health.
        /// </summary>
        public static string Campaign_Health {
            get {
                return ResourceManager.GetString("Campaign_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        public static string China {
            get {
                return ResourceManager.GetString("China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPARE.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it!.
        /// </summary>
        public static string Confirm_button {
            get {
                return ResourceManager.GetString("Confirm_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Costs.
        /// </summary>
        public static string Conversion_Costs {
            get {
                return ResourceManager.GetString("Conversion_Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Rate.
        /// </summary>
        public static string Conversion_Rate {
            get {
                return ResourceManager.GetString("Conversion_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONVERSIONS.
        /// </summary>
        public static string Conversions {
            get {
                return ResourceManager.GetString("Conversions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;bold center-block&quot;&gt; Current&lt;/span&gt; Trend.
        /// </summary>
        public static string Current_Trend {
            get {
                return ResourceManager.GetString("Current_Trend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day {0}.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to England.
        /// </summary>
        public static string England {
            get {
                return ResourceManager.GetString("England", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops....
        /// </summary>
        public static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Error_Message_Button {
            get {
                return ResourceManager.GetString("Error_Message_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        public static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India.
        /// </summary>
        public static string India {
            get {
                return ResourceManager.GetString("India", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        public static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico.
        /// </summary>
        public static string Mexico {
            get {
                return ResourceManager.GetString("Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month {0}.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 month.
        /// </summary>
        public static string One_month {
            get {
                return ResourceManager.GetString("One_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 week.
        /// </summary>
        public static string One_week {
            get {
                return ResourceManager.GetString("One_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 year.
        /// </summary>
        public static string One_year {
            get {
                return ResourceManager.GetString("One_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Sales.
        /// </summary>
        public static string Online_Sales {
            get {
                return ResourceManager.GetString("Online_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Health.
        /// </summary>
        public static string Overall_Health {
            get {
                return ResourceManager.GetString("Overall_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philippines.
        /// </summary>
        public static string Philippines {
            get {
                return ResourceManager.GetString("Philippines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland.
        /// </summary>
        public static string Poland {
            get {
                return ResourceManager.GetString("Poland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPC.
        /// </summary>
        public static string PPC {
            get {
                return ResourceManager.GetString("PPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREVIOUS.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range of days.
        /// </summary>
        public static string Range_of_days {
            get {
                return ResourceManager.GetString("Range_of_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referring Domains.
        /// </summary>
        public static string Referring_Domains {
            get {
                return ResourceManager.GetString("Referring_Domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        public static string Russia {
            get {
                return ResourceManager.GetString("Russia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;Select&lt;/span&gt; Range.
        /// </summary>
        public static string Select_Range {
            get {
                return ResourceManager.GetString("Select_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions by Region.
        /// </summary>
        public static string Sessions_by_Region {
            get {
                return ResourceManager.GetString("Sessions_by_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Trend.
        /// </summary>
        public static string Social_Trend {
            get {
                return ResourceManager.GetString("Social_Trend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Korea.
        /// </summary>
        public static string South_Korea {
            get {
                return ResourceManager.GetString("South_Korea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spend.
        /// </summary>
        public static string Spend {
            get {
                return ResourceManager.GetString("Spend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;lead&quot;&gt;This dashboard is unsupported on small devices.&lt;/p&gt; Much data awaits you! Please switch to a larger screen to see the dashboard in all its glory..
        /// </summary>
        public static string Support_Text {
            get {
                return ResourceManager.GetString("Support_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARGET.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Party.
        /// </summary>
        public static string Third_Party {
            get {
                return ResourceManager.GetString("Third_Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 months.
        /// </summary>
        public static string Three_months {
            get {
                return ResourceManager.GetString("Three_months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Pages.
        /// </summary>
        public static string Top_Pages {
            get {
                return ResourceManager.GetString("Top_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get-to-your-work, the-solution-is-dashboards, ios-controls-help, top-5-UX-projects, make-the-time, if-you-build-it-they-will-come, marketing-projects-with-roi, top-resources-for seo, 10-events-you-must-attend, top-five-reasons-to-buy, 3-secrets-to-building-loyalty, why-customers-are-wrong, ceo-interview, from-red-to-black-in-one-quarter, monthly-sales-goals, summer-extravaganza, unfortunate-turn-of-events, my-iphone-is-my-computer, 7-deadly-assumptions, what-our-customers-wont-say, why-we-love-our-customers [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Top_Pages_List {
            get {
                return ResourceManager.GetString("Top_Pages_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Unbranded Keywords.
        /// </summary>
        public static string Top_Unbranded_Keywords {
            get {
                return ResourceManager.GetString("Top_Unbranded_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to press releases, media coverage, marketing ROI, SEO checklist, online marketing , office management, online payment solutions , online stores, semiconductors, shopping cart solutions, software , startup, technology, transportation, virtual server hosting, web design, web development , web hosting, industrial goods, government and trade, food and beverage, office supplies, biotechnology.
        /// </summary>
        public static string Top_Unbranded_Keywords_List {
            get {
                return ResourceManager.GetString("Top_Unbranded_Keywords_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        public static string United_States {
            get {
                return ResourceManager.GetString("United_States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week {0}.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Marketing Dashboard!.
        /// </summary>
        public static string Welcome_message {
            get {
                return ResourceManager.GetString("Welcome_message", resourceCulture);
            }
        }
    }
}
